# Generated by Django 3.2.3 on 2022-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='avisos',
        ),
        migrations.AlterField(
            model_name='datos',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
