# Generated by Django 3.2.3 on 2022-05-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220514_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResetaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_consumo', models.DateField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicamento')),
            ],
        ),
    ]
